// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMagnet(arg1:string):Promise<void>;

export function AddTorrentFile(arg1:string):Promise<void>;

export function CreateTorrentFromFiles(arg1:Array<string>):Promise<string>;

export function GetBalance():Promise<number>;

export function GetDepositAddress():Promise<string>;

export function GetStats():Promise<main.Stats>;

export function GetTorrent(arg1:string):Promise<main.TorrentInfo>;

export function GetTorrents():Promise<Array<main.TorrentInfo>>;

export function OpenDownloadFolder():Promise<void>;

export function PauseTorrent(arg1:string):Promise<void>;

export function RemoveTorrent(arg1:string,arg2:boolean):Promise<void>;

export function ResumeTorrent(arg1:string):Promise<void>;

export function SelectLocalFiles():Promise<Array<string>>;

export function SelectTorrentFile():Promise<string>;

export function SetDepositAddress(arg1:string):Promise<void>;
