// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMagnet(arg1) {
  return window['go']['main']['App']['AddMagnet'](arg1);
}

export function AddTorrentFile(arg1) {
  return window['go']['main']['App']['AddTorrentFile'](arg1);
}

export function CreateTorrentFromFiles(arg1) {
  return window['go']['main']['App']['CreateTorrentFromFiles'](arg1);
}

export function GetBalance() {
  return window['go']['main']['App']['GetBalance']();
}

export function GetDepositAddress() {
  return window['go']['main']['App']['GetDepositAddress']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTorrent(arg1) {
  return window['go']['main']['App']['GetTorrent'](arg1);
}

export function GetTorrents() {
  return window['go']['main']['App']['GetTorrents']();
}

export function OpenDownloadFolder() {
  return window['go']['main']['App']['OpenDownloadFolder']();
}

export function PauseTorrent(arg1) {
  return window['go']['main']['App']['PauseTorrent'](arg1);
}

export function RemoveTorrent(arg1, arg2) {
  return window['go']['main']['App']['RemoveTorrent'](arg1, arg2);
}

export function ResumeTorrent(arg1) {
  return window['go']['main']['App']['ResumeTorrent'](arg1);
}

export function SelectLocalFiles() {
  return window['go']['main']['App']['SelectLocalFiles']();
}

export function SelectTorrentFile() {
  return window['go']['main']['App']['SelectTorrentFile']();
}

export function SetDepositAddress(arg1) {
  return window['go']['main']['App']['SetDepositAddress'](arg1);
}
