// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMagnet(arg1) {
  return window['go']['main']['App']['AddMagnet'](arg1);
}

export function CreateTorrentFromPath(arg1) {
  return window['go']['main']['App']['CreateTorrentFromPath'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTorrent(arg1) {
  return window['go']['main']['App']['GetTorrent'](arg1);
}

export function GetTorrents() {
  return window['go']['main']['App']['GetTorrents']();
}

export function OpenDownloadFolder() {
  return window['go']['main']['App']['OpenDownloadFolder']();
}

export function PauseTorrent(arg1) {
  return window['go']['main']['App']['PauseTorrent'](arg1);
}

export function RemoveTorrent(arg1, arg2) {
  return window['go']['main']['App']['RemoveTorrent'](arg1, arg2);
}

export function ResumeTorrent(arg1) {
  return window['go']['main']['App']['ResumeTorrent'](arg1);
}

export function SelectSeedPath() {
  return window['go']['main']['App']['SelectSeedPath']();
}
